version: "3"

services:

  app:
    image: node:alpine
    container_name: "hkm_node"
    user: "node"
    working_dir: /home/node/app
    labels:
      - 'traefik.backend=hkm_node'
      - 'traefik.frontend.rule=Host: localhost; PathPrefix: /api'
    environment:
      - NODE_ENV=production
    volumes:
      - ./api:/home/node/app
      - ./api/node_modules:/home/node/node_modules
    expose:
      - "1337"
    # command: "node ./src/server/index.js"
    command: "npm run dev"
    depends_on:
      - mongo

  mongo:
    build:
      context: ./docker
      dockerfile: mongo.dockerfile
    container_name: "hkm_mongo"
    labels:
      - 'traefik.backend=hkm_mongo'
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db

  nginx:
    image: nginx
    container_name: "hkm_nginx"
    labels:
      - 'traefik.backend=hkm_nginx'
      - 'traefik.frontend.rule=Host: localhost'
    volumes:
      - ./www/public:/usr/share/nginx/html

  traefik:
    image: traefik
    container_name: "hkm_traefik"
    command: -c /dev/null --docker --logLevel=INFO
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  mongodata:
